services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_TOKEN=1234567890
      - MESSAGE=FastAPI
    volumes:
      - ./app.py:/app/app.py
    restart: unless-stopped 
